#using scripts\autogenerated\luielems\zm\zm_location;
#using scripts\core_common\array_shared;
#using scripts\core_common\callbacks_shared;
#using scripts\core_common\clientfield_shared;
#using scripts\core_common\flag_shared;
#using scripts\core_common\hud_util_shared;
#using scripts\core_common\laststand_shared;
#using scripts\core_common\struct;
#using scripts\core_common\system_shared;
#using scripts\core_common\util_shared;
#using scripts\zm_common\zm_audio;
#using scripts\zm_common\zm_equipment;
#using scripts\zm_common\zm_stats;
#using scripts\zm_common\zm_unitrigger;
#using scripts\zm_common\zm_utility;
#using scripts\zm_common\zm_weapons;

#namespace zm_hud;

// Namespace zm_hud/zm_hud
// Params 0, eflags: 0x2
// Checksum 0x9f6c52f4, Offset: 0xf8
// Size: 0x54
function autoexec __init__system__() {
    system::register(#"zm_hud", &__init__, &__main__, #"zm_crafting");
}

// Namespace zm_hud/zm_hud
// Params 0, eflags: 0x1 linked
// Checksum 0x72d1db19, Offset: 0x158
// Size: 0x64
function __init__() {
    level.zm_location = zm_location::register("zm_location");
    callback::on_connect(&on_player_connect);
    callback::on_spawned(&on_player_spawned);
}

// Namespace zm_hud/zm_hud
// Params 0, eflags: 0x1 linked
// Checksum 0x80f724d1, Offset: 0x1c8
// Size: 0x4
function __main__() {
    
}

// Namespace zm_hud/zm_hud
// Params 0, eflags: 0x1 linked
// Checksum 0x80f724d1, Offset: 0x1d8
// Size: 0x4
function on_player_connect() {
    
}

// Namespace zm_hud/zm_hud
// Params 0, eflags: 0x1 linked
// Checksum 0x693cc272, Offset: 0x1e8
// Size: 0x9c
function on_player_spawned() {
    self endon(#"disconnect");
    if (level.zm_location zm_location::is_open(self)) {
        level.zm_location zm_location::close(self);
    }
    self.var_b3122c84 = #"";
    util::wait_network_frame();
    if (isdefined(self)) {
        self function_84c3e8e6();
    }
}

// Namespace zm_hud/zm_hud
// Params 0, eflags: 0x1 linked
// Checksum 0xe5d89ffc, Offset: 0x290
// Size: 0x44
function function_84c3e8e6() {
    if (!level.zm_location zm_location::is_open(self)) {
        level.zm_location zm_location::open(self, 0);
    }
}

// Namespace zm_hud/zm_hud
// Params 1, eflags: 0x1 linked
// Checksum 0xc9361a59, Offset: 0x2e0
// Size: 0x8c
function function_29780fb5(location) {
    self.var_5417136 = location;
    if (level.zm_location zm_location::is_open(self)) {
        level.zm_location zm_location::set_location_name(self, location);
        if (self.var_b3122c84 != location) {
            self.var_b3122c84 = location;
            self thread zm_audio::function_a3c4af48(location);
        }
    }
}

