#using scripts\autogenerated\luielems\luielembar;
#using scripts\core_common\burnplayer;

#namespace ct_firebreak_tutorial;

// Namespace ct_firebreak_tutorial/ct_firebreak_tutorial
// Params 0
// Checksum 0x6e7a38c, Offset: 0x88
// Size: 0x26
function init()
{
    level.progress_bar = luielembar::register( "progress_bar" );
}

