#using scripts\autogenerated\luielems\zm\zm_red_challenges_hud;
#using scripts\core_common\ai\zombie_utility;
#using scripts\core_common\array_shared;
#using scripts\core_common\callbacks_shared;
#using scripts\core_common\clientfield_shared;
#using scripts\core_common\exploder_shared;
#using scripts\core_common\flag_shared;
#using scripts\core_common\fx_shared;
#using scripts\core_common\math_shared;
#using scripts\core_common\music_shared;
#using scripts\core_common\scene_shared;
#using scripts\core_common\spawner_shared;
#using scripts\core_common\status_effects\status_effect_util;
#using scripts\core_common\struct;
#using scripts\core_common\util_shared;
#using scripts\core_common\values_shared;
#using scripts\core_common\vehicle_shared;
#using scripts\zm\ai\zm_ai_blight_father;
#using scripts\zm\weapons\zm_weap_hand_charon;
#using scripts\zm\weapons\zm_weap_hand_gaia;
#using scripts\zm\weapons\zm_weap_hand_hemera;
#using scripts\zm\weapons\zm_weap_hand_ouranos;
#using scripts\zm\zm_red;
#using scripts\zm\zm_red_challenges;
#using scripts\zm\zm_red_challenges_rewards;
#using scripts\zm\zm_red_fasttravel;
#using scripts\zm_common\bgbs\zm_bgb_anywhere_but_here;
#using scripts\zm_common\bgbs\zm_bgb_shields_up;
#using scripts\zm_common\util\ai_gegenees_util;
#using scripts\zm_common\zm_aoe;
#using scripts\zm_common\zm_audio;
#using scripts\zm_common\zm_bgb_pack;
#using scripts\zm_common\zm_characters;
#using scripts\zm_common\zm_customgame;
#using scripts\zm_common\zm_devgui;
#using scripts\zm_common\zm_fasttravel;
#using scripts\zm_common\zm_hero_weapon;
#using scripts\zm_common\zm_laststand;
#using scripts\zm_common\zm_loadout;
#using scripts\zm_common\zm_magicbox;
#using scripts\zm_common\zm_player;
#using scripts\zm_common\zm_powerups;
#using scripts\zm_common\zm_round_logic;
#using scripts\zm_common\zm_round_spawning;
#using scripts\zm_common\zm_sq;
#using scripts\zm_common\zm_transformation;
#using scripts\zm_common\zm_unitrigger;
#using scripts\zm_common\zm_utility;
#using scripts\zm_common\zm_vo;
#using scripts\zm_common\zm_weapons;
#using scripts\zm_common\zm_zonemgr;

#namespace red_boss_battle;

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xaf3bcd06, Offset: 0x8a8
// Size: 0xdec
function init() {
    clientfield::register("missile", "" + #"hash_64910f94ebb8d66a", 16000, 2, "int");
    clientfield::register("scriptmover", "" + #"pegasus_emerge", 16000, 1, "counter");
    clientfield::register("scriptmover", "" + #"pegasus_storm", 16000, 1, "int");
    clientfield::register("allplayers", "" + #"hash_73e309ffb25bf63d", 16000, 1, "int");
    clientfield::register("toplayer", "" + #"hash_3bb8b5cda11eecc6", 16000, 1, "counter");
    clientfield::register("scriptmover", "" + #"lightning_impact_fx", 16000, 1, "int");
    clientfield::register("scriptmover", "" + #"lightning_arc_fx", 16000, 1, "int");
    clientfield::register("scriptmover", "" + #"viper_bite_bitten_fx", 16000, 1, "int");
    clientfield::register("scriptmover", "" + #"viper_bite_projectile_impact", 16000, 1, "counter");
    scene::add_scene_func(#"aib_vign_cust_zm_red_boss_intro", &function_e46ef00b, "skip_started");
    level flag::init(#"hash_79d95c7c3d63882d");
    level flag::init(#"hash_315fae99adaebfb4");
    level flag::init(#"hash_7be183aa6a4cbe7");
    level flag::init(#"hash_6dab61ca45a8eaea");
    level flag::init(#"pegasus_attacking");
    level flag::init(#"perseus_attacking");
    level flag::init(#"hash_59553ef93adcfe51");
    level flag::init(#"hash_44d76e9e7b9e0ebd");
    level flag::init(#"hash_15ba89b2357ff618");
    level flag::init(#"hash_75d9474065de2230");
    level flag::init(#"hash_75d94a4065de2749");
    level flag::init(#"hash_3e2ec7f6fb6b50c9");
    level flag::init(#"hash_3e2ec4f6fb6b4bb0");
    level flag::init(#"hash_1c0b421abe38d4e0");
    level flag::init(#"boss_battle_complete");
    zm_sq::register(#"boss_battle", #"stat_tracker", #"stat_tracker", &stat_tracker_setup, &stat_tracker_cleanup, 1);
    zm_sq::start(#"boss_battle");
    level._effect[#"storm_radius"] = #"hash_4dd46a244305d465";
    level._effect[#"annihilator_bolt"] = #"hash_9a8432f2e39c8af";
    level._effect[#"hash_4311fc5f4111c023"] = #"hash_6b0875f1b8c6cf55";
    level._effect[#"hash_4311fd5f4111c1d6"] = #"hash_6b0872f1b8c6ca3c";
    level._effect[#"hash_4311fe5f4111c389"] = #"hash_6b0873f1b8c6cbef";
    level._effect[#"hash_4d8d2bc22add9939"] = #"hash_7a8056b9d995fa0";
    level._effect[#"hash_661c427afb24e5f2"] = #"hash_32b6f16bb5eaa401";
    level._effect[#"hash_65a9f0574c7cd2db"] = #"hash_70f9f9890480fd54";
    level._effect[#"hash_3d64776928022f66"] = #"hash_57449588f6051a0d";
    level._effect[#"perseus_death"] = #"hash_6c3beeb5851adca4";
    level.s_boss_battle = spawnstruct();
    level.s_boss_battle.var_35345d3d = getent("vol_boss_arena_1", "targetname");
    level.s_boss_battle.var_285e59dd = getent("vol_boss_arena_2", "targetname");
    level.s_boss_battle.var_76f4f0e9 = getent("vol_boss_arena_3", "targetname");
    level.s_boss_battle.var_2624492f = [];
    level.s_boss_battle.var_2624492f[2] = "fountain_miniboss_ent";
    level.s_boss_battle.var_2624492f[3] = "column_miniboss_ent";
    level.s_boss_battle.var_2624492f[1] = "park_miniboss_ent";
    level.s_boss_battle.s_pinnacle = struct::get("s_pinnacle_center");
    level.s_boss_battle.var_98ea549b = getent("no_aoe", "targetname");
    level.s_boss_battle.var_5203fa2b = struct::get_array("boss_attack_point");
    level.s_boss_battle.registersarah_defeated_gore_ = struct::get_array("boss_2_player_respawn");
    level.s_boss_battle.var_415fc88 = 33;
    level.s_boss_battle.n_stage = 0;
    level.s_boss_battle.var_dc656db3 = 0;
    level.s_boss_battle.mdl_perseus = getent("chaos_bolt_thrower", "targetname");
    level.s_boss_battle.mdl_perseus hide();
    level.s_boss_battle.var_c67e8352 = getent("chaos_bolt_thrower_shield", "targetname");
    level.s_boss_battle.var_c67e8352 hide();
    level.s_boss_battle.var_5e9e4c15 = getent("chaos_bolt_thrower_sword", "targetname");
    level.s_boss_battle.var_5e9e4c15 hide();
    level.s_boss_battle.mdl_perseus val::set("zm_red_boss_fight", "takedamage", 1);
    level.s_boss_battle.mdl_perseus val::set("zm_red_boss_fight", "allowdeath", 1);
    level.s_boss_battle.mdl_perseus.health = 99999;
    level.s_boss_battle.mdl_perseus.b_override_explosive_damage_cap = 1;
    level.s_boss_battle.var_d82d0e73 = array(level.s_boss_battle.mdl_perseus, level.s_boss_battle.var_c67e8352, level.s_boss_battle.var_5e9e4c15);
    level.s_boss_battle.var_b7fe5d46 = 20000;
    level.s_boss_battle.var_36f0e240 = 0;
    level.s_boss_battle.var_4652a428 = 6;
    level.s_boss_battle.var_ad3f929f = 0;
    level.s_boss_battle.var_1e4f5dab = 15000;
    level.s_boss_battle.mdl_perseus.var_c164e6c7 = 3;
    level.s_boss_battle.var_5dc26e42 = 0;
    level.s_boss_battle.var_7fc7f236 = 15000;
    level.s_boss_battle.var_5db6ed5f = getweapon("perseus_bolt_projectile");
    level.s_boss_battle.var_86d9f46c = getstatuseffect(#"hash_19533caf858a9f3b");
    level.s_boss_battle.var_b42f3b39 = getstatuseffect(#"hash_12a64221f4d27f9b");
    /#
        if (zm_utility::is_ee_enabled()) {
            setdvar(#"hash_336a4b6a4bdec400", 0);
            setdvar(#"hash_2c5a53140f377a17", 0);
            setdvar(#"hash_16d0c8f49c9e0090", 0);
            setdvar(#"hash_3031043ff4ac0395", 0);
            setdvar(#"hash_68b9a321eca18c32", 0);
            adddebugcommand("<dev string:x38>");
            adddebugcommand("<dev string:x9c>");
            adddebugcommand("<dev string:x104>");
            adddebugcommand("<dev string:x165>");
            adddebugcommand("<dev string:x1c7>");
            adddebugcommand("<dev string:x227>");
            adddebugcommand("<dev string:x288>");
            adddebugcommand("<dev string:x2f0>");
            level.s_boss_battle.var_5de58d03 = 0;
            zm_devgui::add_custom_devgui_callback(&function_27486895);
            adddebugcommand("<dev string:x35a>");
            adddebugcommand("<dev string:x3af>");
            adddebugcommand("<dev string:x403>");
            level thread function_d5a70078();
        }
    #/
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x43295c86, Offset: 0x16a0
// Size: 0x24
function function_e46ef00b(a_ents) {
    exploder::stop_exploder("fxexp_boss_intro_sh01");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x2d5dadd5, Offset: 0x16d0
// Size: 0x76
function function_a4bcce4e() {
    for (i = 0; i < 4; i++) {
        str_bgb = self.bgb_pack[i];
        if (str_bgb === #"zm_bgb_immolation_liquidation") {
            self bgb_pack::function_b2308cd(i, 3);
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 3, eflags: 0x0
// Checksum 0x767e498d, Offset: 0x1750
// Size: 0x864
function function_3a2efd4e(b_cheated = 0, var_7982b1c8 = 1, var_8ef91a04 = 1) {
    level endon(#"end_game", #"hash_7646638df88a3656");
    level flag::wait_till("zones_initialized");
    level._zombiemode_check_firesale_loc_valid_func = &return_false;
    array::thread_all(getplayers(), &function_a4bcce4e);
    zombie_utility::set_zombie_var(#"zombie_powerup_fire_sale_on", 0);
    level notify(#"fire_sale_off");
    callback::on_spawned(&on_player_spawned);
    callback::on_connect(&on_player_connect);
    if (b_cheated) {
        level flag::set("power_on");
        level flag::set(#"pap_quest_completed");
        level flag::set(#"zm_red_fasttravel_open");
        /#
            if (getdvarint(#"hash_36841a9b10fd186d", 0)) {
                var_7982b1c8 = 0;
            } else {
                level scene::init_streamer(#"aib_vign_cust_zm_red_boss_intro", #"allies");
            }
        #/
    }
    foreach (chest in level.chests) {
        chest zm_magicbox::hide_chest(0);
    }
    foreach (player in getplayers()) {
        player disableweaponfire();
    }
    level.musicsystemoverride = 1;
    zm_red_challenges::function_304fb042();
    if (var_7982b1c8) {
        music::setmusicstate("boss_battle_intro_igc");
        level scene::play(#"aib_vign_cust_zm_red_boss_intro");
    }
    foreach (player in getplayers()) {
        player enableweaponfire();
    }
    level.s_boss_battle.mdl_perseus show();
    level.s_boss_battle.var_c67e8352 show();
    level.s_boss_battle.var_5e9e4c15 show();
    if (!(isdefined(level.var_27a02034) && level.var_27a02034)) {
        scene::add_scene_func("aib_vign_cust_zm_red_boss2_intro_exit", &function_21ef9bb7);
    }
    level thread scene::play("boss_intro_exit", "targetname");
    zombie_utility::set_zombie_var(#"zombie_powerup_drop_max_per_round", 9);
    zm_round_spawning::function_376e51ef(#"skeleton");
    zm_round_spawning::function_376e51ef(#"gegenees");
    level function_3de660a0();
    level clientfield::set("" + #"hash_71f9fcfb2cd84a9c", 1);
    zm_zonemgr::enable_zone("zone_boss_plateau_1");
    zm_zonemgr::enable_zone("zone_boss_plateau_2");
    zm_zonemgr::enable_zone("zone_boss_plateau_3");
    var_9dc587a9 = struct::get_array("s_boss_arena_teleport");
    a_players = getplayers();
    for (i = 0; i < a_players.size; i++) {
        if (var_8ef91a04) {
            a_players[i] setorigin(var_9dc587a9[i].origin);
            a_players[i] setplayerangles(var_9dc587a9[i].angles);
        }
        a_players[i] thread function_9099e4d8();
        foreach (var_de3a312c in level.var_3958c9ff) {
            a_players[i] thread zm_red_fasttravel::function_28deccf1(var_de3a312c, 1);
        }
        a_players[i] thread function_6401a80e();
        a_players[i] thread function_1722dae1();
    }
    level.var_6f6cc58 = &function_123b6625;
    level.var_4e4950d1 = &function_20c2dd32;
    zm_red::function_eeb6a1e7();
    e_vo_player = array::random(util::get_active_players(#"allies"));
    if (isdefined(e_vo_player)) {
        e_vo_player thread zm_vo::function_a2bd5a0c(#"hash_607c594be89dec0e", 2);
    }
    level thread function_f6306dea();
    music::setmusicstate("boss_battle_stage_1");
    wait 3;
    level thread function_756474bf();
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xb594bda0, Offset: 0x1fc0
// Size: 0x404
function function_dfaf17c8() {
    level.s_boss_battle.n_stage = 0;
    level.s_boss_battle.var_dc656db3 = 0;
    level.s_boss_battle.var_b7fe5d46 = 20000;
    level.s_boss_battle.var_36f0e240 = 0;
    level.s_boss_battle.var_4652a428 = 6;
    level.s_boss_battle.var_ad3f929f = 0;
    level.s_boss_battle.var_1e4f5dab = 15000;
    level.s_boss_battle.mdl_perseus.var_c164e6c7 = 3;
    level.s_boss_battle.var_5dc26e42 = 0;
    level.s_boss_battle.var_7fc7f236 = 15000;
    level.s_boss_battle.mdl_perseus.origin = level.s_boss_battle.s_pinnacle.origin;
    level.s_boss_battle.var_2624492f = [];
    level.s_boss_battle.var_2624492f[2] = "fountain_miniboss_ent";
    level.s_boss_battle.var_2624492f[3] = "column_miniboss_ent";
    level.s_boss_battle.var_2624492f[1] = "park_miniboss_ent";
    exploder::stop_exploder("fxexp_boss_pers_area_denial_forest");
    exploder::stop_exploder("fxexp_boss_pers_area_denial_fountain");
    exploder::stop_exploder("exp_lgt_boss_isle_1");
    exploder::stop_exploder("exp_lgt_boss_isle_2");
    level flag::clear(#"hash_75d9474065de2230");
    level flag::clear(#"hash_75d94a4065de2749");
    level flag::clear(#"hash_3e2ec7f6fb6b50c9");
    level flag::clear(#"hash_3e2ec4f6fb6b4bb0");
    level flag::clear(#"hash_15ba89b2357ff618");
    foreach (var_de3a312c in level.var_3958c9ff) {
        var_de3a312c.var_5a099a2d = undefined;
        var_de3a312c.var_151f9e4b = undefined;
        foreach (player in getplayers()) {
            player thread zm_red_fasttravel::function_28deccf1(var_de3a312c, 1);
        }
    }
    level flag::clear(#"hash_315fae99adaebfb4");
    level flag::clear(#"perseus_attacking");
    level flag::clear(#"hash_59553ef93adcfe51");
    level flag::clear(#"pegasus_attacking");
    function_e4f860ab();
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xe5cbfa61, Offset: 0x23d0
// Size: 0x4c
function on_player_spawned() {
    self function_9099e4d8();
    self thread function_1722dae1();
    self thread function_6401a80e();
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xec08bd12, Offset: 0x2428
// Size: 0x6e
function function_9099e4d8() {
    if (isdefined(self.var_424c161e) && self.var_424c161e) {
        if (isdefined(self.var_cad44cf2)) {
            self giveweapon(self.var_cad44cf2);
            return;
        }
        self takeweapon(level.w_thunderstorm);
        self.var_424c161e = 0;
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x835d6533, Offset: 0x24a0
// Size: 0x26c
function function_3de660a0() {
    level.var_b2b15659 = 1;
    level.powerup_vo_available = &return_false;
    level zm_audio::function_6191af93(#"general", #"gib", "", "");
    level zm_audio::function_6191af93(#"elixir", #"drink", "", "");
    level zm_audio::function_6191af93(#"blight_father", #"weak_points", "", "");
    level zm_audio::function_6191af93(#"catalyst_transform", #"react", "", "");
    level zm_audio::function_6191af93(#"catalyst_water", #"react", "", "");
    level zm_audio::function_6191af93(#"catalyst_electric", #"react", "", "");
    level zm_audio::function_6191af93(#"catalyst_plasma", #"react", "", "");
    level zm_audio::function_6191af93(#"catalyst_corrosive", #"react", "", "");
    level zm_audio::function_6191af93(#"catalyst_corrosive", #"react", "", "");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x92d0177, Offset: 0x2718
// Size: 0x8e4
function function_756474bf() {
    level endon(#"hash_7646638df88a3656");
    level flag::set("pause_round_timeout");
    callback::on_player_damage(&function_4cd6f3d3);
    level.var_e120ae98 = &function_60d4faca;
    level.custom_spawnplayer = &function_9bc4f8cb;
    zm_bgb_anywhere_but_here::function_886fce8f(0);
    level.zombie_round_start_delay = 0;
    level.zombie_powerups[#"fire_sale"].func_should_drop_with_regular_powerups = &return_false;
    level.zombie_powerups[#"bonus_points_team"].func_should_drop_with_regular_powerups = &return_false;
    level.zombie_powerups[#"bonus_points_player"].func_should_drop_with_regular_powerups = &return_false;
    level.zombie_powerups[#"bonus_points_player_shared"].func_should_drop_with_regular_powerups = &return_false;
    if (!isdefined(level.var_d6f059f7)) {
        level.var_d6f059f7 = max(level.round_number, 25);
    }
    level.var_5d1805c4 = &function_d899c62c;
    switch (level.players.size) {
    case 1:
        var_12e5a581 = 7;
        level.s_boss_battle.var_415fc88 = 15;
        level.s_boss_battle.var_2f02900b = 1;
        level.s_boss_battle.var_b7fe5d46 = 9000;
        level.s_boss_battle.var_7fc7f236 = 12000;
        level.s_boss_battle.var_1e4f5dab = 10000;
        level.s_boss_battle.var_407b6d64 = 5000;
        break;
    case 2:
        var_12e5a581 = 10;
        level.s_boss_battle.var_415fc88 = 20;
        level.s_boss_battle.var_2f02900b = 2;
        level.s_boss_battle.var_b7fe5d46 = 12000;
        level.s_boss_battle.var_7fc7f236 = 15000;
        level.s_boss_battle.var_1e4f5dab = 12000;
        level.s_boss_battle.var_407b6d64 = 7000;
        break;
    case 3:
        var_12e5a581 = 12;
        level.s_boss_battle.var_415fc88 = 25;
        level.s_boss_battle.var_2f02900b = 3;
        level.s_boss_battle.var_b7fe5d46 = 15000;
        level.s_boss_battle.var_7fc7f236 = 10000;
        level.s_boss_battle.var_1e4f5dab = 10000;
        level.s_boss_battle.var_407b6d64 = 9000;
        break;
    case 4:
        var_12e5a581 = 15;
        level.s_boss_battle.var_415fc88 = 33;
        level.s_boss_battle.var_2f02900b = 3;
        level.s_boss_battle.var_b7fe5d46 = 18000;
        level.s_boss_battle.var_7fc7f236 = 25000;
        level.s_boss_battle.var_1e4f5dab = 15000;
        level.s_boss_battle.var_407b6d64 = 15000;
        break;
    }
    /#
        if (getdvarint(#"zm_debug_ee", 0)) {
            level.s_boss_battle.var_b7fe5d46 = 200;
            level.s_boss_battle.var_f4660320 = 2;
            level.s_boss_battle.var_9d0225ce = 50000;
        }
    #/
    level.zombie_ai_limit = level.s_boss_battle.var_2f02900b;
    function_8b1f9518();
    level thread function_517bbfad(level.s_boss_battle.var_2f02900b);
    while (level.s_boss_battle.var_dc656db3 == 0) {
        waitframe(1);
    }
    level flag::set(#"hash_79d95c7c3d63882d");
    zm_bgb_anywhere_but_here::function_886fce8f();
    level.zombie_ai_limit = var_12e5a581;
    level flag::wait_till(#"hash_315fae99adaebfb4");
    wait 3;
    level thread function_263a0b8();
    level flag::wait_till_timeout(300, #"hash_15ba89b2357ff618");
    if (flag::get(#"pegasus_attacking")) {
        wait 3;
    }
    function_79611ef0(1);
    level flag::wait_till(#"hash_6dab61ca45a8eaea");
    level flag::wait_till_clear(#"pegasus_attacking");
    level flag::clear("spawn_zombies");
    level zm_utility::function_9ad5aeb1(0, 1, 1, 0);
    function_54c795f6();
    level notify(#"boss_stage_1_done");
    level flag::set(#"hash_7be183aa6a4cbe7");
    /#
        if (getdvarint(#"zm_debug_ee", 0)) {
            iprintlnbold("<dev string:x45c>");
        }
    #/
    level.s_boss_battle.mdl_perseus function_c7a3202c("zone_boss_plateau_2");
    level.s_boss_battle.mdl_perseus scene::play(#"aib_vign_cust_zm_red_boss1_stg2_to_stg3_01", level.s_boss_battle.var_d82d0e73);
    function_4d844f2();
    level thread function_170c8b16();
    function_79611ef0(2);
    e_vo_player = array::random(util::get_active_players(#"allies"));
    if (isdefined(e_vo_player)) {
        e_vo_player thread zm_vo::function_a2bd5a0c(#"hash_67e6464e20e49efb", 1);
    }
    function_54c795f6();
    level.s_boss_battle.mdl_perseus function_c7a3202c("zone_boss_plateau_2");
    function_4d844f2();
    level thread function_14833fc2();
    function_e4f860ab();
    level flag::set("spawn_zombies");
    level thread function_290d42b8();
    level flag::wait_till(#"hash_6dab61ca45a8eaea");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xc2c7021b, Offset: 0x3008
// Size: 0x6a
function function_e4f860ab() {
    level flag::clear(#"hash_6dab61ca45a8eaea");
    level flag::clear(#"hash_7be183aa6a4cbe7");
    level.s_boss_battle.var_5dc26e42 = 0;
    level.s_boss_battle.var_36f0e240 = 0;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x1fae4239, Offset: 0x3080
// Size: 0x54
function function_8b1f9518() {
    if (isdefined(level.s_boss_battle.mdl_perseus)) {
        level.s_boss_battle.mdl_perseus zm_vo::vo_say(#"hash_177261226759d391", 0, 1, 9999);
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xf9c89855, Offset: 0x30e0
// Size: 0xac
function function_170c8b16() {
    level.s_boss_battle.mdl_perseus zm_vo::vo_say(#"hash_43413288a913e03", 0, 1, 9999);
    wait 1;
    e_vo_player = array::random(util::get_active_players(#"allies"));
    if (isdefined(e_vo_player)) {
        e_vo_player thread zm_vo::function_a2bd5a0c(#"hash_6589e76f2431dda0", 1);
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xa301c827, Offset: 0x3198
// Size: 0xe4
function function_b8510127() {
    level.s_boss_battle.var_64801233.origin = self.origin + anglestoforward(self.angles) * -3900 + anglestoright(self.angles) * -130 + (0, 0, -160);
    level.s_boss_battle.var_64801233.angles = (0, randomintrange(0, 360), 0);
    waitframe(1);
    level.s_boss_battle.var_64801233 clientfield::increment("" + #"pegasus_emerge");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x4fe6c7bc, Offset: 0x3288
// Size: 0x148
function function_b3df51ad(a_ents) {
    level endon(#"hash_4be6553c5ac0ec2b", #"hash_7646638df88a3656");
    e_pegasus = self.scene_ents[#"pegasus"];
    e_pegasus.health = 100000;
    /#
        if (getdvarint(#"zm_debug_ee", 0)) {
            e_pegasus thread function_213d02bd();
        }
    #/
    while (true) {
        level waittill(#"bombs_away");
        v_drop_point = e_pegasus zm_utility::groundpos(e_pegasus.origin);
        if (v_drop_point[2] > 600 && !function_85593a2(v_drop_point)) {
            zm_aoe::function_371b4147(4, #"zm_aoe_strafe_storm", v_drop_point);
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x6cdc6d74, Offset: 0x33d8
// Size: 0x47a
function chaos_bolt_thrower(e_target) {
    e_perseus = level.s_boss_battle.mdl_perseus;
    v_target_pos = e_target.origin;
    if (level.s_boss_battle.n_stage != 4) {
        level waittill(#"artillery_out");
    }
    var_5f07628 = e_perseus gettagorigin("tag_weapon_right");
    if (isplayer(e_target)) {
        projectile = magicbullet(level.s_boss_battle.var_5db6ed5f, var_5f07628, v_target_pos, e_perseus);
        if (level.s_boss_battle.n_stage > 1) {
            projectile clientfield::set("" + #"hash_64910f94ebb8d66a", 2);
        } else {
            projectile clientfield::set("" + #"hash_64910f94ebb8d66a", 1);
        }
        b_annihilator = 0;
    } else {
        projectile = magicbullet(level.s_boss_battle.var_5db6ed5f, var_5f07628, v_target_pos, e_perseus);
        projectile clientfield::set("" + #"hash_64910f94ebb8d66a", 3);
        b_annihilator = 1;
    }
    s_result = projectile waittilltimeout(7, #"projectile_impact_explode", #"projectile_impact_player", #"projectile_impact");
    if (s_result._notify === #"timeout") {
        return;
    } else if (s_result._notify === #"projectile_impact_player") {
        if (isdefined(s_result.player)) {
            v_pos = getclosestpointonnavmesh(s_result.player.origin, 128, 16);
        }
    } else if (s_result._notify === #"projectile_impact_explode" || s_result._notify === #"projectile_impact") {
        if (isdefined(s_result.position)) {
            v_pos = getclosestpointonnavmesh(s_result.position, 128, 16);
        }
    }
    if (isdefined(v_pos)) {
        playsoundatposition(#"hash_2a8cdf7d7ef28efe", v_pos);
        if (b_annihilator) {
            zm_aoe::function_371b4147(7, #"zm_aoe_chaos_bolt_annihilate", v_pos);
            return;
        }
        if (function_85593a2(v_pos)) {
            return 0;
        }
        switch (level.s_boss_battle.n_stage) {
        case 0:
        case 1:
            zm_aoe::function_371b4147(5, #"zm_aoe_chaos_bolt", v_pos);
            break;
        case 2:
        case 3:
            zm_aoe::function_371b4147(6, #"zm_aoe_chaos_bolt_2", v_pos);
            break;
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x4
// Checksum 0x5a9e1816, Offset: 0x3860
// Size: 0x202
function private function_9e8c41f4(e_target) {
    level endon(#"perseus_defeated", #"hash_7646638df88a3656");
    e_target endon(#"death");
    str_target_zone = e_target function_732c74f7(3);
    if (!isdefined(str_target_zone)) {
        return false;
    }
    b_finished = 0;
    while (!b_finished) {
        self function_c7a3202c(str_target_zone);
        /#
            if (getdvarint(#"zm_debug_ee", 0)) {
                var_701a257e = "<dev string:x48a>";
                switch (str_target_zone) {
                case #"zone_boss_plateau_1":
                    var_701a257e = "<dev string:x494>";
                    break;
                case #"zone_boss_plateau_2":
                    var_701a257e = "<dev string:x49f>";
                    break;
                case #"zone_boss_plateau_3":
                    var_701a257e = "<dev string:x4a8>";
                    break;
                }
                iprintlnbold("<dev string:x4af>" + var_701a257e + "<dev string:x4c2>" + (isdefined(e_target) ? e_target.playernum : "<dev string:x4d1>"));
            }
        #/
        var_59d19c72 = e_target function_732c74f7(3);
        if (!isdefined(var_59d19c72)) {
            return false;
        }
        if (var_59d19c72 == str_target_zone) {
            b_finished = 1;
        } else {
            str_target_zone = var_59d19c72;
        }
        waitframe(1);
    }
    return true;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x4407a0fa, Offset: 0x3a70
// Size: 0x2b4
function function_20bfbc00(a_ents) {
    level endon(#"hash_4d25b32acbac5117");
    if (isarray(a_ents)) {
        a_keys = getarraykeys(a_ents);
        if (isinarray(a_keys, #"pegasus")) {
            e_boss = self.scene_ents[#"pegasus"];
            self thread function_ca661e4b(1);
        } else if (isinarray(a_keys, #"boss_1")) {
            e_boss = self.scene_ents[#"boss_1"];
        }
    }
    if (!isdefined(e_boss)) {
        return;
    }
    e_boss.zm_ai_category = #"boss";
    e_boss.team = #"axis";
    e_boss clientfield::set("" + #"special_target", 1);
    if (!function_ffa5b184(e_boss)) {
        e_boss function_2baad8fc();
    }
    if (!isdefined(level.var_2c19331b)) {
        level.var_2c19331b = [];
    } else if (!isarray(level.var_2c19331b)) {
        level.var_2c19331b = array(level.var_2c19331b);
    }
    if (!isinarray(level.var_2c19331b, e_boss)) {
        level.var_2c19331b[level.var_2c19331b.size] = e_boss;
    }
    arrayremovevalue(level.var_2c19331b, undefined);
    e_boss thread function_26acf7ee();
    e_boss thread function_2858e671(#"damage");
    level thread function_2858e671(#"hero_weapon_hit", e_boss);
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x1b6abe03, Offset: 0x3d30
// Size: 0x8c
function function_aa23278d(a_ents) {
    e_perseus = self.scene_ents[#"boss_1"];
    if (isdefined(e_perseus.var_e0418003)) {
        str_fx = #"hash_3a2097ef26fdafe0" + e_perseus.var_e0418003;
        e_perseus fx::play(level._effect[str_fx]);
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 2, eflags: 0x0
// Checksum 0x454429eb, Offset: 0x3dc8
// Size: 0x300
function function_2858e671(var_c34665fc, e_boss) {
    level endon(#"hash_4d25b32acbac5117", #"hash_7646638df88a3656");
    self endon(#"death");
    while (true) {
        s_waitresult = self waittill(var_c34665fc);
        self.health = 100000;
        if (var_c34665fc == #"damage") {
            e_attacker = s_waitresult.attacker;
            w_weapon = s_waitresult.weapon;
        } else if (var_c34665fc == #"hero_weapon_hit") {
            e_attacker = s_waitresult.player;
            w_weapon = s_waitresult.var_80e17549;
        }
        if (zm_loadout::is_hero_weapon(w_weapon)) {
            n_damage = e_attacker function_12f4c281(s_waitresult, w_weapon, e_boss);
        } else {
            continue;
        }
        if (isdefined(n_damage) && n_damage > 0) {
            level.s_boss_battle.var_5dc26e42 += n_damage;
            if (level.s_boss_battle.n_stage == 1) {
                if (level.s_boss_battle.var_5dc26e42 >= level.s_boss_battle.var_7fc7f236 / 2) {
                    level flag::set(#"hash_15ba89b2357ff618");
                }
                var_391b5374 = level.s_boss_battle.var_7fc7f236;
            } else if (level.s_boss_battle.n_stage == 3) {
                var_391b5374 = level.s_boss_battle.var_407b6d64;
            }
            /#
                iprintlnbold("<dev string:x4d8>" + level.s_boss_battle.var_5dc26e42 + "<dev string:x4e9>" + var_391b5374);
            #/
            if (level.s_boss_battle.var_5dc26e42 >= var_391b5374) {
                level flag::set(#"hash_6dab61ca45a8eaea");
            }
            if (isdefined(e_attacker) && isplayer(e_attacker)) {
                self function_4c17036d(e_attacker, 1);
            }
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 3, eflags: 0x0
// Checksum 0xa0245c05, Offset: 0x40d0
// Size: 0x820
function function_12f4c281(s_waitresult, w_weapon, e_boss) {
    str_notify = s_waitresult._notify;
    n_lvl = self.var_72d6f15d;
    str_weapon = self.var_b708af7b;
    var_e635b6cb = 50 * n_lvl;
    if (str_notify === "damage") {
        if (isinarray(level.hero_weapon[#"chakram"], w_weapon)) {
            if (w_weapon === level.hero_weapon[#"chakram"][2] && s_waitresult.mod === "MOD_UNKNOWN") {
                var_7bf2d9c0 = 1;
            } else if (s_waitresult.mod === "MOD_PROJECTILE") {
                var_b162218f = 1;
            }
        }
        if (isinarray(level.hero_weapon[#"scepter"], w_weapon) && s_waitresult.mod === "MOD_BURNED") {
            if (isdefined(self.var_d6fe2916) && self.var_d6fe2916) {
                var_c408ccc9 = 1;
            } else {
                return 0;
            }
        }
        if (isinarray(level.hero_weapon[#"hammer"], w_weapon)) {
            if (isdefined(s_waitresult.mod)) {
                switch (s_waitresult.mod) {
                case #"mod_electrocuted":
                    var_b7f8cbd8 = 1;
                    break;
                case #"mod_unknown":
                    var_3ae8e8aa = 1;
                    break;
                }
            }
        }
        if (isinarray(level.hero_weapon[#"sword_pistol"], w_weapon)) {
            if (s_waitresult.mod === "MOD_EXPLOSIVE") {
                return 0;
            } else if (w_weapon === level.hero_weapon[#"sword_pistol"][2] && s_waitresult.mod === "MOD_PROJECTILE") {
                var_b46b719c = 1;
            }
        }
    } else if (str_notify === "hero_weapon_hit" && s_waitresult.e_entity === e_boss) {
        if (isinarray(level.hero_weapon[#"scepter"], w_weapon)) {
            var_5b0fafb = 1;
        }
        if (isinarray(level.hero_weapon[#"sword_pistol"], w_weapon)) {
            var_99f536ed = 1;
        }
    }
    switch (str_weapon) {
    case #"chakram":
        if (str_notify === "damage") {
            if (isdefined(var_b162218f) && var_b162218f) {
                n_base_damage = 100;
                /#
                    str_damage_type = "<dev string:x4f0>";
                #/
            } else if (isdefined(var_7bf2d9c0) && var_7bf2d9c0) {
                n_base_damage = 25;
                var_e635b6cb = 0;
                /#
                    str_damage_type = "<dev string:x500>";
                #/
            } else {
                n_base_damage = 50;
                /#
                    str_damage_type = "<dev string:x510>";
                #/
            }
        }
        break;
    case #"scepter":
        if (str_notify === "hero_weapon_hit") {
            if (isdefined(var_5b0fafb) && var_5b0fafb) {
                n_base_damage = 25;
                var_e635b6cb = 0;
                /#
                    str_damage_type = "<dev string:x520>";
                #/
            }
        } else if (str_notify === "damage") {
            if (isdefined(var_c408ccc9) && var_c408ccc9) {
                n_base_damage = 50;
                var_e635b6cb = 0;
                /#
                    str_damage_type = "<dev string:x52f>";
                #/
            } else {
                n_base_damage = 150;
                /#
                    str_damage_type = "<dev string:x540>";
                #/
            }
        }
        break;
    case #"hammer":
        if (str_notify === "damage") {
            if (isdefined(var_3ae8e8aa) && var_3ae8e8aa) {
                n_base_damage = 6;
                var_e635b6cb = 0;
                /#
                    str_damage_type = "<dev string:x550>";
                #/
            } else if (isdefined(var_b7f8cbd8) && var_b7f8cbd8) {
                n_base_damage = 80;
                var_e635b6cb = 0;
                /#
                    str_damage_type = "<dev string:x55f>";
                #/
            } else {
                n_base_damage = 100;
                /#
                    str_damage_type = "<dev string:x572>";
                #/
            }
        }
        break;
    case #"sword_pistol":
        if (str_notify === "hero_weapon_hit") {
            if (isdefined(var_99f536ed) && var_99f536ed) {
                n_base_damage = 100;
                /#
                    str_damage_type = "<dev string:x581>";
                #/
            }
        } else if (str_notify === "damage") {
            if (isdefined(var_b46b719c) && var_b46b719c) {
                n_base_damage = 900;
                /#
                    str_damage_type = "<dev string:x58f>";
                #/
            } else {
                n_base_damage = 100;
                /#
                    str_damage_type = "<dev string:x59c>";
                #/
            }
        }
        break;
    default:
        n_base_damage = 100;
        /#
            str_damage_type = "<dev string:x5aa>";
        #/
        break;
    }
    if (!isdefined(n_base_damage)) {
        n_base_damage = 0;
        var_e635b6cb = 0;
        /#
            if (getdvarint(#"zm_debug_ee", 0)) {
            }
        #/
    }
    /#
        if (getdvarint(#"zm_debug_ee", 0)) {
            if (isdefined(str_damage_type)) {
                iprintlnbold(str_damage_type + "<dev string:x5b5>" + n_base_damage + var_e635b6cb);
            }
            if (!isdefined(level.s_boss_battle.var_5015427)) {
                level.s_boss_battle.var_5015427 = [];
            } else if (!isarray(level.s_boss_battle.var_5015427)) {
                level.s_boss_battle.var_5015427 = array(level.s_boss_battle.var_5015427);
            }
            if (!isdefined(level.s_boss_battle.var_5015427[self.playernum])) {
                level.s_boss_battle.var_5015427[self.playernum] = 0;
            }
            level.s_boss_battle.var_5015427[self.playernum] += n_base_damage + var_e635b6cb;
        }
    #/
    return n_base_damage + var_e635b6cb;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xd3f1da08, Offset: 0x48f8
// Size: 0x1da
function function_26acf7ee() {
    self notify("ff57fe675953cb3");
    self endon("ff57fe675953cb3");
    /#
        if (getdvarint(#"zm_debug_ee", 0)) {
            level.s_boss_battle.var_5f00964 = level.s_boss_battle.var_5dc26e42;
            level.s_boss_battle.var_5015427 = [];
            if (getdvar(#"hash_68b9a321eca18c32", 0)) {
                setdvar(#"hash_3031043ff4ac0395", 0);
            }
        }
    #/
    level waittill(#"hash_4d25b32acbac5117", #"perseus_defeated");
    if (isdefined(self)) {
        self clientfield::set("" + #"special_target", 0);
    }
    level.var_2c19331b = array::exclude(level.var_2c19331b, self);
    /#
        if (getdvarint(#"zm_debug_ee", 0)) {
            level.s_boss_battle.var_35fffce1 = level.s_boss_battle.var_5dc26e42 - level.s_boss_battle.var_5f00964;
            if (getdvar(#"hash_68b9a321eca18c32", 0)) {
                level.s_boss_battle.var_5dc26e42 = 0;
            }
        }
    #/
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xb68d7a1, Offset: 0x4ae0
// Size: 0x44
function function_4cd6f3d3(eventstruct) {
    if (eventstruct.eattacker === level.s_boss_battle.mdl_perseus) {
        zm_hero_weapon::function_3fe4a02e(self, 125);
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xa4596c3b, Offset: 0x4b30
// Size: 0x19c
function function_517bbfad(var_2f02900b) {
    level endon(#"end_game");
    level flag::clear("spawn_zombies");
    callback::on_ai_killed(&function_a362f6ed);
    callback::on_ai_spawned(&function_5e02e791);
    level scene::play("column_miniboss_ent", "targetname");
    if (var_2f02900b > 1) {
        level thread function_9d06f858(#"hash_1bc4862b9138d947");
        level thread function_9d06f858(#"hash_3f87a91683ebe8e3");
    }
    level flag::set("spawn_zombies");
    while (level.s_boss_battle.var_dc656db3 < var_2f02900b) {
        waitframe(1);
    }
    callback::remove_on_ai_killed(&function_a362f6ed);
    callback::remove_on_ai_spawned(&function_5e02e791);
    level flag::set(#"hash_315fae99adaebfb4");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xee04e084, Offset: 0x4cd8
// Size: 0x3a
function function_5e02e791() {
    if (self.archetype === #"gegenees") {
        self.b_ignore_cleanup = 1;
        self.var_126d7bef = 1;
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x26ec542b, Offset: 0x4d20
// Size: 0x3c
function function_a362f6ed(s_params) {
    if (self.archetype === #"gegenees") {
        level.s_boss_battle.var_dc656db3++;
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x85f8aa06, Offset: 0x4d68
// Size: 0xea
function function_9d06f858(var_fb8c33cc) {
    level endon(#"game_end");
    level flag::wait_till(var_fb8c33cc);
    if (level.s_boss_battle.var_2f02900b > level.s_boss_battle.var_dc656db3) {
        switch (var_fb8c33cc) {
        case #"hash_1bc4862b9138d947":
            level scene::play("fountain_miniboss_ent", "targetname");
            break;
        case #"hash_3f87a91683ebe8e3":
            level scene::play("park_miniboss_ent", "targetname");
            break;
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x8e27fec9, Offset: 0x4e60
// Size: 0x25c
function function_263a0b8() {
    level endon(#"hash_7646638df88a3656");
    level flag::clear("spawn_zombies");
    level thread function_14833fc2();
    level flag::set(#"infinite_round_spawning");
    level.s_boss_battle.n_stage = 1;
    level.s_boss_battle.var_5dc26e42 = 0;
    level.s_boss_battle.var_64801233 = util::spawn_model("tag_origin");
    if (!(isdefined(level.var_1a1d3c82) && level.var_1a1d3c82)) {
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss2_atk_01", &function_b3df51ad, "play");
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss2_atk_01", &function_21ef9bb7);
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss2_atk_01", &function_21ef9bb7, "fail_end");
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss2_atk_01", &function_20bfbc00, "fail_start");
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss2_atk_01", &function_cb86284d, "fail_end");
        level.var_1a1d3c82 = 1;
    }
    level thread function_7a7b5e79();
    level util::waittill_level_any_timeout(10, level, #"hash_4be6553c5ac0ec2b");
    level flag::set("spawn_zombies");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xd7116e83, Offset: 0x50c8
// Size: 0x3d0
function function_f6306dea() {
    level endon(#"perseus_defeated", #"hash_3496e98116b2be19", #"hash_7646638df88a3656");
    e_perseus = level.s_boss_battle.mdl_perseus;
    if (!(isdefined(level.var_42ea19b1) && level.var_42ea19b1)) {
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss1_stg1_chaos_atk_01", &function_aa23278d);
        level.var_42ea19b1 = 1;
    }
    while (true) {
        while (level flag::get(#"hash_59553ef93adcfe51")) {
            level flag::set(#"hash_44d76e9e7b9e0ebd");
            wait 0.2;
        }
        level flag::clear(#"hash_44d76e9e7b9e0ebd");
        if (math::cointoss()) {
            e_perseus scene::play(#"aib_vign_cust_zm_red_boss1_stg3_idle_01", level.s_boss_battle.var_d82d0e73);
        } else {
            e_perseus scene::play(#"aib_vign_cust_zm_red_boss1_stg1_summon_01", level.s_boss_battle.var_d82d0e73);
            if (level.s_boss_battle.n_stage > 0) {
                level thread spawn_miniboss();
            }
        }
        if (!level flag::get(#"hash_59553ef93adcfe51")) {
            level flag::wait_till_clear(#"perseus_attacking");
            level flag::set(#"perseus_attacking");
            if (level.s_boss_battle.n_stage == 3) {
                var_c47b0cbf = 0;
                /#
                    if (getdvarint(#"hash_16d0c8f49c9e0090", 0)) {
                        var_c47b0cbf = 1;
                    }
                #/
                if (math::cointoss() || var_c47b0cbf) {
                    level thread function_4a58a0(e_perseus);
                    level waittill(#"hash_78452700119fc913");
                } else {
                    level thread function_d9802986();
                    level util::waittill_level_any_timeout(13, level, #"hash_47a15209e6e6fc14");
                }
                level thread function_84fac8d5(2, 1);
            } else {
                e_perseus.var_e0418003 = 2;
                level thread function_d9802986();
                level util::waittill_level_any_timeout(13, level, #"hash_47a15209e6e6fc14");
            }
            e_perseus.var_e0418003 = 1;
            level flag::clear(#"perseus_attacking");
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xc7849284, Offset: 0x54a0
// Size: 0x20e
function function_7a7b5e79() {
    level endon(#"boss_stage_1_done", #"hash_7646638df88a3656");
    _town_pap_quest_complete = 0;
    var_22f02aa3 = struct::get_array("boss_attack_1");
    for (s_loc = struct::get("first_strike", "script_string"); true; s_loc = undefined) {
        while (level flag::get(#"hash_7be183aa6a4cbe7") || level flag::get(#"hash_6dab61ca45a8eaea")) {
            wait 1;
        }
        level flag::set(#"pegasus_attacking");
        var_22f02aa3 = array::filter(var_22f02aa3, 0, &function_a695c70b);
        if (!isdefined(s_loc)) {
            s_loc = array::random(var_22f02aa3);
        }
        if (isdefined(level.s_boss_battle.var_5de58d03) && level.s_boss_battle.var_5de58d03) {
            s_loc = var_22f02aa3[0];
        }
        s_loc function_b8510127();
        wait 1.1;
        s_loc thread function_ca661e4b(0, _town_pap_quest_complete);
        s_loc function_1ce83bec();
        level flag::clear(#"pegasus_attacking");
        _town_pap_quest_complete++;
        wait level.s_boss_battle.var_4652a428;
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xf1a8d325, Offset: 0x56b8
// Size: 0x210
function function_1ce83bec() {
    level endon(#"hash_7646638df88a3656");
    self scene::play(#"aib_vign_cust_zm_red_boss2_atk_01", "start");
    if (level.s_boss_battle.var_36f0e240 >= level.s_boss_battle.var_b7fe5d46) {
        level notify(#"boss_stunned");
        level thread function_14833fc2();
        self scene::play(#"aib_vign_cust_zm_red_boss2_atk_01", "fail_start");
        self thread scene::play(#"aib_vign_cust_zm_red_boss2_atk_01", "fail_loop");
        var_c5374ab4 = 7;
        if (getdvarint(#"zm_debug_ee", 0)) {
            if (getdvarint(#"hash_3031043ff4ac0395", 0)) {
                var_c5374ab4 = 60;
            }
        }
        wait var_c5374ab4;
        level notify(#"hash_4d25b32acbac5117");
        self scene::play(#"aib_vign_cust_zm_red_boss2_atk_01", "fail_end");
        level.s_boss_battle.var_36f0e240 = 0;
    } else {
        /#
            iprintlnbold("<dev string:x5c0>" + level.s_boss_battle.var_36f0e240);
        #/
        self scene::play(#"aib_vign_cust_zm_red_boss2_atk_01", "atk_end");
    }
    level notify(#"hash_4be6553c5ac0ec2b");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x2f8123a4, Offset: 0x58d0
// Size: 0x5c
function function_8e7ffff8() {
    self endon(#"death");
    level waittill(#"hash_4be6553c5ac0ec2b", #"hash_7646638df88a3656");
    wait 1;
    if (isdefined(self)) {
        self delete();
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 3, eflags: 0x0
// Checksum 0xb867bdf, Offset: 0x5938
// Size: 0x462
function function_84fac8d5(var_956f2977, n_delay, v_origin) {
    if (isdefined(v_origin)) {
        a_e_players = array::get_all_closest(v_origin, util::get_active_players(#"allies"));
    } else {
        a_e_players = array::randomize(util::get_active_players(#"allies"));
    }
    switch (var_956f2977) {
    case 0:
        var_b628ac68 = #"hash_5d787cea8ef3883a";
        n_cooldown = randomintrange(3, 7);
        if (!isdefined(level.var_cf52cfd3)) {
            level.var_cf52cfd3 = 0;
        }
        var_10b0c19e = level.var_cf52cfd3 - level.s_boss_battle.var_5dc26e42;
        break;
    case 1:
        var_b628ac68 = #"hash_d41a1c9041dea26";
        n_cooldown = randomintrange(2, 5);
        break;
    case 2:
        var_b628ac68 = #"hash_5dfb705eb4fffef";
        n_cooldown = randomintrange(3, 7);
        if (!isdefined(level.var_d6bf4d87)) {
            level.var_d6bf4d87 = 0;
        }
        var_10b0c19e = level.var_d6bf4d87 - level.s_boss_battle.var_5dc26e42;
        break;
    case 3:
        var_b628ac68 = #"hash_248248312e0377c1";
        n_cooldown = randomintrange(2, 5);
        break;
    }
    if (!isdefined(var_b628ac68)) {
        return 0;
    }
    if (isdefined(var_10b0c19e) && var_10b0c19e >= 0) {
        return 0;
    }
    foreach (e_player in a_e_players) {
        if (!isdefined(e_player.var_fea99aef)) {
            e_player.var_fea99aef = [];
        } else if (!isarray(e_player.var_fea99aef)) {
            e_player.var_fea99aef = array(e_player.var_fea99aef);
        }
        if (!isdefined(e_player.var_fea99aef[var_956f2977]) || !e_player.var_fea99aef[var_956f2977]) {
            if (var_956f2977 == 1 || var_956f2977 == 3) {
                if (e_player gadgetpowerget(level.var_a53a05b5) < 100) {
                    continue;
                }
            }
            e_player thread zm_vo::function_a2bd5a0c(var_b628ac68, n_delay);
            e_player.var_fea99aef[var_956f2977] = n_cooldown;
            if (var_956f2977 == 0) {
                level.var_cf52cfd3 = level.s_boss_battle.var_5dc26e42;
            } else if (var_956f2977 == 2) {
                level.var_d6bf4d87 = level.s_boss_battle.var_5dc26e42;
            }
            return 1;
        }
        e_player.var_fea99aef[var_956f2977]--;
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 2, eflags: 0x4
// Checksum 0x6c391a10, Offset: 0x5da8
// Size: 0x1ea
function private function_ca661e4b(var_956f2977, _town_pap_quest_complete) {
    switch (var_956f2977) {
    case 0:
        if (!_town_pap_quest_complete) {
            level.s_boss_battle.mdl_perseus zm_vo::vo_say(#"hash_504e6e3f0da7a9df", 0, 1, 9999);
            a_e_players = array::get_all_closest(self.origin, util::get_active_players(#"allies"));
            foreach (e_player in a_e_players) {
                if (zm_utility::is_player_valid(e_player)) {
                    e_vo_player = e_player;
                    break;
                }
            }
            if (isdefined(e_vo_player)) {
                e_vo_player zm_vo::function_a2bd5a0c(#"hash_2c9021dcd1e62316", 1);
            }
        } else {
            function_84fac8d5(0, 2, self.origin);
        }
        break;
    case 1:
        function_84fac8d5(1, 2, level.s_boss_battle.mdl_perseus.origin);
        break;
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xed26fc47, Offset: 0x5fa0
// Size: 0x458
function function_21ef9bb7(a_ents) {
    level endon(#"hash_4be6553c5ac0ec2b", #"boss_stunned", #"hash_6b4f82e61af7cb08");
    if (isarray(a_ents)) {
        a_keys = getarraykeys(a_ents);
        if (isinarray(a_keys, #"pegasus")) {
            e_boss = self.scene_ents[#"pegasus"];
            var_653b9351 = 1;
            /#
                str_boss = "<dev string:x5d4>";
            #/
            e_boss thread function_8e7ffff8();
        } else if (isinarray(a_keys, #"boss_1")) {
            e_boss = self.scene_ents[#"boss_1"];
            var_653b9351 = 0;
            /#
                str_boss = "<dev string:x5de>";
            #/
        }
    }
    if (!isdefined(e_boss)) {
        return;
    }
    e_boss endon(#"death");
    level thread function_5fc81f0a(e_boss);
    e_boss.zm_ai_category = #"boss";
    e_boss setteam("axis");
    target_set(e_boss);
    if (!function_ffa5b184(e_boss)) {
        e_boss function_2baad8fc();
    }
    while (true) {
        s_waitresult = e_boss waittill(#"damage", #"death");
        e_boss.health = 100000;
        if (s_waitresult._notify === "death") {
            return;
        }
        e_attacker = s_waitresult.attacker;
        if (isdefined(e_attacker) && isplayer(e_attacker)) {
            e_boss function_4c17036d(e_attacker);
        }
        if (var_653b9351) {
            level.s_boss_battle.var_36f0e240 += s_waitresult.amount;
        } else if (zm_weapons::function_35746b9c(s_waitresult.weapon)) {
            level.s_boss_battle.var_ad3f929f += 50;
            /#
                if (getdvarint(#"zm_debug_ee", 0)) {
                    s_waitresult.amount = 50;
                }
            #/
        } else {
            level.s_boss_battle.var_ad3f929f += s_waitresult.amount;
        }
        /#
            if (getdvarint(#"zm_debug_ee", 0)) {
                if (var_653b9351 || !var_653b9351 && !(isdefined(e_boss.var_c3505998) && e_boss.var_c3505998)) {
                    iprintlnbold(str_boss + "<dev string:x5e8>" + s_waitresult.amount + "<dev string:x5f2>");
                }
            }
        #/
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xc02f6580, Offset: 0x6400
// Size: 0x3b0
function function_d9802986() {
    self notify("1e89b8ab1ad1c3c6");
    self endon("1e89b8ab1ad1c3c6");
    level endon(#"perseus_defeated", #"hash_7646638df88a3656");
    s_pinnacle = struct::get("s_pinnacle_center");
    e_perseus = level.s_boss_battle.mdl_perseus;
    b_target_found = 0;
    e_target = undefined;
    while (!b_target_found) {
        a_e_active_players = util::get_active_players(#"allies");
        a_e_active_players = array::randomize(a_e_active_players);
        if (a_e_active_players.size > 1) {
            foreach (e_active_player in a_e_active_players) {
                if (zm_utility::is_player_valid(e_active_player) && !(isdefined(e_active_player.var_16735873) && e_active_player.var_16735873) && e_perseus.var_56b1208a !== e_active_player && !e_active_player istouching(level.s_boss_battle.var_98ea549b)) {
                    e_target = e_active_player;
                }
            }
        } else {
            e_target = a_e_active_players[0];
        }
        if (!isdefined(e_target)) {
            wait 0.3;
            continue;
        }
        b_target_found = 1;
    }
    e_perseus.var_56b1208a = e_target;
    b_success = e_perseus function_9e8c41f4(e_target);
    if (isdefined(b_success) && b_success) {
        if (!isdefined(e_perseus.var_90e23166)) {
            e_perseus.var_90e23166 = 5;
        }
        if (!e_perseus.var_90e23166) {
            e_perseus thread zm_vo::vo_say(#"hash_7565b085198b71db", 0, 1, 9999);
            e_perseus.var_90e23166 = randomintrangeinclusive(8, 17);
        } else {
            e_perseus.var_90e23166--;
        }
        level thread chaos_bolt_thrower(e_target);
        e_perseus scene::play(#"aib_vign_cust_zm_red_boss1_stg1_chaos_atk_01", level.s_boss_battle.var_d82d0e73);
    } else {
        /#
            if (getdvarint(#"zm_debug_ee", 0)) {
                iprintlnbold("<dev string:x5fc>" + (isdefined(e_target) ? e_target.playernum : "<dev string:x4d1>") + "<dev string:x610>");
            }
        #/
    }
    level notify(#"hash_47a15209e6e6fc14");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x4
// Checksum 0x99ac7635, Offset: 0x67b8
// Size: 0xde
function private function_732c74f7(n_max_time) {
    str_target_zone = self zm_zonemgr::get_player_zone();
    n_time = 0;
    while (!isdefined(str_target_zone)) {
        wait 0.3;
        n_time += 0.3;
        if (isdefined(n_max_time)) {
            if (n_time > n_max_time) {
                /#
                    if (getdvarint(#"zm_debug_ee", 0)) {
                        iprintlnbold("<dev string:x632>" + n_max_time);
                    }
                #/
                return;
            }
        }
        str_target_zone = self zm_zonemgr::get_player_zone();
    }
    return str_target_zone;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x4
// Checksum 0xd2c89d14, Offset: 0x68a0
// Size: 0x86
function private function_3c2238ed(str_zone) {
    n_island = 0;
    switch (str_zone) {
    case #"zone_boss_plateau_1":
        n_island = 2;
        break;
    case #"zone_boss_plateau_2":
        n_island = 3;
        break;
    case #"zone_boss_plateau_3":
        n_island = 1;
        break;
    }
    return n_island;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xe7bb4d86, Offset: 0x6930
// Size: 0x154
function function_cb86284d(a_ents) {
    level endon(#"hash_7646638df88a3656");
    e_pegasus = a_ents[#"pegasus"];
    if (isdefined(e_pegasus)) {
        level waittill(#"start_thunderstorm");
        var_1d708692 = zm_utility::groundpos(e_pegasus.origin);
        str_zone = zm_zonemgr::get_zone_from_position(var_1d708692);
        if (!isdefined(str_zone)) {
            return;
        }
        switch (str_zone) {
        case #"zone_boss_plateau_1":
            n_isle = 2;
            break;
        case #"zone_boss_plateau_2":
            n_isle = 3;
            break;
        case #"zone_boss_plateau_3":
            n_isle = 1;
            break;
        }
        function_b2420fe0(n_isle);
        level thread function_b4723f8e(var_1d708692, e_pegasus);
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 2, eflags: 0x4
// Checksum 0x179934b2, Offset: 0x6a90
// Size: 0x294
function private function_b4723f8e(v_origin, e_pegasus) {
    mdl_origin = spawn("script_model", v_origin);
    mdl_origin setmodel("tag_origin");
    mdl_origin clientfield::set("" + #"pegasus_storm", 1);
    n_radius = 256;
    for (n_iterations = int(20); n_iterations > 0; n_iterations--) {
        foreach (e_player in getplayers()) {
            if (!isalive(e_player)) {
                continue;
            }
            n_radius_squared = n_radius * n_radius;
            if (distancesquared(e_player.origin, v_origin) < n_radius_squared) {
                e_player clientfield::set("" + #"hash_73e309ffb25bf63d", 1);
                e_player thread lightning_flash();
                e_player status_effect::status_effect_apply(level.s_boss_battle.var_86d9f46c, undefined, e_pegasus);
                e_player dodamage(10, v_origin);
            }
        }
        wait 0.5;
        if (n_radius < 1000) {
            n_radius = math::clamp(n_radius + 50, 256, 1000);
        }
    }
    mdl_origin clientfield::set("" + #"pegasus_storm", 0);
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xe6e5d2ca, Offset: 0x6d30
// Size: 0x8c
function lightning_flash() {
    self clientfield::set_to_player("" + #"pegasus_shellshock", 1);
    self clientfield::increment_to_player("" + #"hash_3bb8b5cda11eecc6");
    wait 0.25;
    self clientfield::set_to_player("" + #"pegasus_shellshock", 0);
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x4
// Checksum 0x3af1c904, Offset: 0x6dc8
// Size: 0x1b2
function private function_325b6d95(v_origin) {
    level endon(#"hash_7646638df88a3656");
    n_radius = 1000;
    n_iterations = int(20);
    w_fire = getweapon(#"incendiary_fire");
    while (n_iterations > 0) {
        foreach (e_player in getplayers()) {
            if (!isalive(e_player)) {
                continue;
            }
            n_radius_squared = n_radius * n_radius;
            if (distancesquared(e_player.origin, v_origin) < n_radius_squared) {
                e_player status_effect::status_effect_apply(level.s_boss_battle.var_b42f3b39, w_fire, level.s_boss_battle.mdl_perseus, 0);
                e_player dodamage(10, v_origin);
            }
        }
        wait 0.5;
        n_iterations--;
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x25f69705, Offset: 0x6f88
// Size: 0x22a
function function_290d42b8(b_skipped = 0) {
    level endon(#"hash_7646638df88a3656");
    if (b_skipped) {
        level notify(#"boss_stage_1_done");
    }
    level.s_boss_battle.mdl_perseus.var_c164e6c7 = 3;
    level.s_boss_battle.n_stage = 3;
    /#
        iprintlnbold("<dev string:x664>" + level.s_boss_battle.n_stage + "<dev string:x66c>");
    #/
    level thread function_14833fc2();
    if (level.activeplayers.size == 4) {
        level.s_boss_battle.var_415fc88 = 50;
    }
    if (!(isdefined(level.var_bd36bb6e) && level.var_bd36bb6e)) {
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss1_stg3_chrg_atk_01", &function_e069d23c);
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss1_stg3_chrg_atk_01", &function_21ef9bb7);
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss1_stg3_chrg_atk_01", &function_20bfbc00, "fail_start");
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss1_stg3_chrg_atk_01", &function_2a866d1a, "atk_end");
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss1_stg3_to_dth_01", &function_20bfbc00);
        level.var_bd36bb6e = 1;
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xa5a90534, Offset: 0x71c0
// Size: 0x640
function function_4a58a0(e_perseus) {
    level endon(#"hash_71d7e6a55a1ca9e", #"hash_7646638df88a3656");
    /#
        if (getdvarint(#"zm_debug_ee", 0)) {
            e_perseus thread function_213d02bd();
        }
    #/
    s_target = array::random(level.s_boss_battle.var_5203fa2b);
    v_destination = s_target.origin;
    if (!isdefined(e_perseus.var_cd1eedcd) || !e_perseus.var_cd1eedcd) {
        if (!isdefined(e_perseus.var_8ba6a643)) {
            e_perseus.var_8ba6a643 = 0;
        }
        var_10b0c19e = e_perseus.var_8ba6a643 - level.s_boss_battle.var_5dc26e42;
        if (var_10b0c19e < 0) {
            e_perseus thread zm_vo::vo_say(#"hash_4690d77cb085e0c8", 0, 1, 9999);
            e_perseus.var_cd1eedcd = randomintrangeinclusive(3, 7);
            e_perseus.var_8ba6a643 = level.s_boss_battle.var_5dc26e42;
        }
    } else {
        e_perseus.var_cd1eedcd--;
    }
    level thread perseus_teleport_fx(v_destination);
    e_perseus scene::play(#"aib_vign_cust_zm_red_boss1_stg3_teleport_start_01", level.s_boss_battle.var_d82d0e73);
    e_perseus.origin = v_destination;
    e_perseus.angles = s_target.angles;
    level thread function_766fb0b1(e_perseus.origin);
    level thread perseus_teleport_fx((20323.7, 21819.1, 1419.25));
    e_perseus scene::play(#"aib_vign_cust_zm_red_boss1_stg3_chrg_atk_01", "start", level.s_boss_battle.var_d82d0e73);
    if (level.s_boss_battle.var_ad3f929f >= level.s_boss_battle.var_1e4f5dab) {
        level thread function_14833fc2();
        level notify(#"hash_6b4f82e61af7cb08");
        level thread function_84fac8d5(3, 1);
        e_perseus thread scene::play(#"aib_vign_cust_zm_red_boss1_stg3_chrg_atk_01", "fail_start", level.s_boss_battle.var_d82d0e73);
        /#
            e_perseus.var_c3505998 = 1;
        #/
        var_c5374ab4 = 7;
        if (getdvarint(#"zm_debug_ee", 0)) {
            if (getdvarint(#"hash_3031043ff4ac0395", 0)) {
                var_c5374ab4 = 60;
            }
        }
        wait var_c5374ab4;
        if (level flag::get(#"hash_6dab61ca45a8eaea")) {
            level notify(#"perseus_defeated");
            e_perseus thread function_caa7eeb();
            level flag::wait_till(#"hash_1c0b421abe38d4e0");
            foreach (player in getplayers()) {
                if (isdefined(player) && player clientfield::get_to_player("" + #"hash_403e80cafccc207c")) {
                    player clientfield::set_to_player("" + #"hash_403e80cafccc207c", 0);
                }
            }
            level thread function_ce82050b();
            level notify(#"hash_71d7e6a55a1ca9e");
        }
        e_perseus scene::play(#"aib_vign_cust_zm_red_boss1_stg3_chrg_atk_01", "fail_end", level.s_boss_battle.var_d82d0e73);
        /#
            e_perseus.var_c3505998 = 0;
        #/
        level notify(#"hash_4d25b32acbac5117");
        level.s_boss_battle.var_ad3f929f = 0;
    } else {
        e_perseus scene::play(#"aib_vign_cust_zm_red_boss1_stg3_chrg_atk_01", "atk_end", level.s_boss_battle.var_d82d0e73);
    }
    e_perseus.origin = level.s_boss_battle.s_pinnacle.origin;
    e_perseus.angles = (0, 90, 0);
    level notify(#"hash_78452700119fc913");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x880dfd3e, Offset: 0x7808
// Size: 0x1ae
function function_2a866d1a(a_ents) {
    level endon(#"end_game");
    e_perseus = level.s_boss_battle.mdl_perseus;
    var_5287d229 = anglestoforward(e_perseus.angles);
    for (i = 0; i <= 10; i++) {
        n_yaw = 36 * i + 22;
        var_bbaa9da2 = var_5287d229 + (0, n_yaw, 0);
        v_direction = anglestoforward(var_bbaa9da2);
        v_target_loc = e_perseus.origin + v_direction;
        launchvelocity = vectornormalize(v_target_loc - e_perseus.origin) * 800;
        projectile = e_perseus magicmissile(level.s_boss_battle.var_5db6ed5f, v_target_loc + (16, 0, 54), launchvelocity);
        projectile clientfield::set("" + #"hash_64910f94ebb8d66a", 3);
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x3e04cb27, Offset: 0x79c0
// Size: 0x74
function function_ab699e09() {
    self clientfield::set("" + #"special_target", 0);
    exploder::stop_exploder("fxexp_barrier_arena");
    self scene::play(#"aib_vign_cust_zm_red_boss1_stg3_to_dth_01", level.s_boss_battle.var_d82d0e73);
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x53647951, Offset: 0x7a40
// Size: 0x3dc
function function_caa7eeb() {
    music::setmusicstate("none");
    level.musicsystemoverride = 0;
    self thread function_ab699e09();
    level flag::clear("spawn_zombies");
    level thread cleanup_final();
    foreach (player in getplayers()) {
        player val::set("game_over_man", "takedamage", 0);
    }
    if (!zm_utility::is_trials()) {
        level scene::function_27f5972e(#"cin_zm_red_outro_temple");
        level scene::init_streamer(#"cin_zm_red_outro_temple", #"allies", 0, 0);
    }
    self zm_vo::vo_say(#"hash_34171dfc4d06ae4b", 0, 1, 9999);
    level.var_92830991 = util::spawn_model(#"hash_7ad70aa7f6e8c41f", self.origin + (0, 0, 48), self.angles);
    level.var_92830991 setscale(4);
    level.var_92830991 thread zm_red_challenges_rewards::function_51fd2597(0);
    level.var_92830991 thread zm_red_challenges_rewards::function_f7cdf2f7(2);
    playfx(level._effect[#"perseus_death"], level.var_92830991.origin - (0, 0, 16));
    array::run_all(level.s_boss_battle.var_d82d0e73, &ghost);
    array::run_all(level.s_boss_battle.var_d82d0e73, &notsolid);
    e_vo_player = array::random(util::get_active_players(#"allies"));
    if (isdefined(e_vo_player)) {
        e_vo_player zm_vo::function_a2bd5a0c(#"hash_2b8d0adc9ec3b069");
    }
    var_791705a1 = level.var_92830991 zm_unitrigger::function_fac87205(&function_662093d4, 64);
    level.var_92830991 delete();
    var_791705a1 zm_vo::function_a2bd5a0c(#"hash_213d18d49a47d63b");
    level flag::set(#"hash_1c0b421abe38d4e0");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x9f6bf122, Offset: 0x7e28
// Size: 0x68
function function_662093d4(player) {
    str_prompt = zm_utility::function_d6046228(#"hash_16d3e1ce95636700", #"hash_54d93a685e1f42c");
    self sethintstringforplayer(player, str_prompt);
    return true;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x450a6228, Offset: 0x7e98
// Size: 0x17c
function function_e069d23c(a_ents) {
    level endon(#"hash_3032e59c42d961c5", #"hash_6b4f82e61af7cb08", #"hash_7646638df88a3656");
    level waittill(#"boss_melee_hit");
    e_perseus = level.s_boss_battle.mdl_perseus;
    v_loc = e_perseus gettagorigin("tag_weapon_right");
    var_c23ba302 = spawn("trigger_radius", v_loc, 0, 192, 32);
    foreach (e_player in level.players) {
        if (e_player istouching(var_c23ba302)) {
            e_player dodamage(150, v_loc, e_perseus);
        }
    }
    var_c23ba302 delete();
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x75fab4ce, Offset: 0x8020
// Size: 0x60
function function_ce82050b() {
    level flag::set(#"boss_battle_complete");
    if (zm_utility::is_trials()) {
        return;
    }
    level zm_red::play_outro();
    level notify(#"end_game");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x4
// Checksum 0x293f986f, Offset: 0x8088
// Size: 0x1dc
function private function_123b6625(e_player) {
    if (!isdefined(e_player) || !isdefined(self)) {
        return false;
    }
    var_fe34d2c5 = self istouching(level.s_boss_battle.var_35345d3d);
    var_c58285e2 = e_player istouching(level.s_boss_battle.var_35345d3d);
    var_b517b5b0 = self istouching(level.s_boss_battle.var_285e59dd);
    var_ba5e5578 = e_player istouching(level.s_boss_battle.var_285e59dd);
    var_363b4c7a = self istouching(level.s_boss_battle.var_76f4f0e9);
    var_5692580b = e_player istouching(level.s_boss_battle.var_76f4f0e9);
    if (!var_363b4c7a && !var_b517b5b0 && !var_fe34d2c5) {
        return false;
    }
    if (var_fe34d2c5 && var_ba5e5578 || var_fe34d2c5 && var_5692580b) {
        return false;
    }
    if (var_b517b5b0 && var_5692580b || var_b517b5b0 && var_c58285e2) {
        return false;
    }
    if (var_363b4c7a && !var_5692580b) {
        return false;
    }
    return true;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x4
// Checksum 0xe9d2a830, Offset: 0x8270
// Size: 0x3a
function private function_20c2dd32(poi) {
    reachable = self function_123b6625(poi[1]);
    return reachable;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x4
// Checksum 0x16b56b49, Offset: 0x82b8
// Size: 0x68
function private function_14833fc2() {
    if (zm_utility::is_trials()) {
        return;
    }
    target_round = zm_round_logic::get_round_number() + 1;
    zm_round_logic::set_round_number(target_round - 1);
    level notify(#"kill_round_wait");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 2, eflags: 0x0
// Checksum 0xdc28aa19, Offset: 0x8328
// Size: 0x134
function function_d899c62c(base_health, round_number) {
    var_d082c739 = base_health;
    round_number = level.var_d6f059f7;
    for (i = 2; i <= round_number; i++) {
        if (i >= 10 && !(isdefined(level.var_50dd0ec5) && level.var_50dd0ec5)) {
            old_health = var_d082c739;
            var_d082c739 += int(var_d082c739 * zombie_utility::get_zombie_var(#"zombie_health_increase_multiplier"));
            if (var_d082c739 < old_health) {
                var_d082c739 = old_health;
                break;
            }
            continue;
        }
        var_d082c739 = int(var_d082c739 + zombie_utility::get_zombie_var(#"zombie_health_increase"));
    }
    return var_d082c739;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x4
// Checksum 0xd0f7472e, Offset: 0x8468
// Size: 0xe4
function private function_54c795f6() {
    level endon(#"hash_7646638df88a3656");
    if (level flag::get(#"hash_59553ef93adcfe51")) {
        /#
            if (getdvarint(#"zm_debug_ee", 0)) {
                iprintlnbold("<dev string:x677>");
            }
        #/
        level flag::wait_till_clear(#"hash_59553ef93adcfe51");
        wait 0.2;
    }
    level flag::set(#"hash_59553ef93adcfe51");
    level flag::wait_till(#"hash_44d76e9e7b9e0ebd");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x4
// Checksum 0xfe85b8fe, Offset: 0x8558
// Size: 0x24
function private function_4d844f2() {
    level flag::clear(#"hash_59553ef93adcfe51");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x699012b4, Offset: 0x8588
// Size: 0x408
function function_79611ef0(n_island) {
    level endon(#"hash_7646638df88a3656");
    e_perseus = level.s_boss_battle.mdl_perseus;
    switch (n_island) {
    case 1:
        var_46285 = level.s_boss_battle.var_76f4f0e9;
        var_3c7cb573 = struct::get("isle_1_powerup");
        var_6a56e928 = "zone_boss_plateau_3";
        str_exploder = "fxexp_boss_pers_area_denial_forest";
        break;
    case 2:
        var_46285 = level.s_boss_battle.var_35345d3d;
        var_3c7cb573 = struct::get("isle_2_powerup");
        var_6a56e928 = "zone_boss_plateau_1";
        str_exploder = "fxexp_boss_pers_area_denial_fountain";
        break;
    }
    level.s_boss_battle.var_2624492f[n_island] = undefined;
    function_54c795f6();
    /#
        if (getdvarint(#"zm_debug_ee", 0)) {
            iprintlnbold("<dev string:x4af>" + (n_island == 1 ? "<dev string:x6ac>" : "<dev string:x494>") + "<dev string:x6b5>");
        }
    #/
    e_perseus function_c7a3202c(var_6a56e928);
    level flag::set(#"hash_44af125ee5c05d21" + n_island);
    function_2003ebc9(n_island);
    exploder::exploder(str_exploder);
    level thread function_325b6d95(var_3c7cb573.origin);
    if (!(isdefined(level.var_aa83d388) && level.var_aa83d388)) {
        scene::add_scene_func(#"aib_vign_cust_zm_red_boss1_stg1_meteor_strike_01", &function_a3f19534, "play");
        level.var_aa83d388 = 1;
    }
    e_perseus scene::play(#"aib_vign_cust_zm_red_boss1_stg1_meteor_strike_01", level.s_boss_battle.var_d82d0e73);
    function_4d844f2();
    level flag::set(#"hash_268e0da84abacda2" + n_island);
    str_exploder = "exp_lgt_boss_isle_" + n_island;
    exploder::exploder(str_exploder);
    function_75f1dc3a(n_island);
    foreach (e_player in util::get_active_players(#"allies")) {
        if (e_player istouching(var_46285)) {
            e_player zm_laststand::instakill_player();
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xbd6a4e98, Offset: 0x8998
// Size: 0xe0
function function_a3f19534(a_ents) {
    if (isdefined(a_ents[#"boss_1"])) {
        a_ents[#"boss_1"] waittill(#"final_strike_here");
        foreach (player in getplayers()) {
            if (isdefined(player)) {
                player playrumbleonentity("zm_red_step_complete_rumble");
            }
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x4
// Checksum 0xecc216c2, Offset: 0x8a80
// Size: 0x306
function private function_2003ebc9(n_island) {
    foreach (var_225a75b4 in level.var_4775015b) {
        switch (n_island) {
        case 1:
            if (var_225a75b4.script_string === "column_to_park" || var_225a75b4.script_string === "fountain_to_park") {
                var_225a75b4.var_5a099a2d = 1;
                array::thread_all(util::get_players(#"allies"), &zm_red_fasttravel::function_28deccf1, var_225a75b4, 0);
                var_225a75b4.unitrigger_stub thread util::delay_notify(0.1, "cancel_fasttravel_cooldown");
            }
            if (var_225a75b4.script_string === "park_to_column" || var_225a75b4.script_string === "park_to_fountain") {
                var_225a75b4.var_151f9e4b = 1;
                var_225a75b4.unitrigger_stub thread util::delay_notify(0.1, "cancel_fasttravel_cooldown");
            }
            break;
        case 2:
            if (var_225a75b4.script_string === "column_to_fountain" || var_225a75b4.script_string === "park_to_fountain") {
                var_225a75b4.var_5a099a2d = 1;
                array::thread_all(util::get_players(#"allies"), &zm_red_fasttravel::function_28deccf1, var_225a75b4, 0);
                var_225a75b4.unitrigger_stub thread util::delay_notify(0.1, "cancel_fasttravel_cooldown");
            }
            if (var_225a75b4.script_string === "fountain_to_column" || var_225a75b4.script_string === "fountain_to_park") {
                var_225a75b4.var_151f9e4b = 1;
                var_225a75b4.unitrigger_stub thread util::delay_notify(0.1, "cancel_fasttravel_cooldown");
            }
            break;
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x4
// Checksum 0xd16057aa, Offset: 0x8d90
// Size: 0x1c6
function private function_75f1dc3a(n_island) {
    foreach (var_225a75b4 in level.var_4775015b) {
        switch (n_island) {
        case 1:
            if (var_225a75b4.script_string === "park_to_column" || var_225a75b4.script_string === "park_to_fountain") {
                var_225a75b4.var_5a099a2d = 1;
                array::thread_all(util::get_players(#"allies"), &zm_red_fasttravel::function_28deccf1, var_225a75b4, 0);
            }
            break;
        case 2:
            if (var_225a75b4.script_string === "fountain_to_column" || var_225a75b4.script_string === "fountain_to_park") {
                var_225a75b4.var_5a099a2d = 1;
                array::thread_all(util::get_players(#"allies"), &zm_red_fasttravel::function_28deccf1, var_225a75b4, 0);
            }
            break;
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x85727ac3, Offset: 0x8f60
// Size: 0x2cc
function function_b2420fe0(n_island) {
    switch (n_island) {
    case 2:
        if (level flag::get(#"hash_75d9474065de2230")) {
            var_888ae42 = struct::get("isle_3_powerup");
        } else {
            var_78a8b445 = struct::get("isle_3_powerup");
            var_888ae42 = struct::get("isle_1_powerup");
        }
        break;
    case 3:
        if (level flag::get(#"hash_75d9474065de2230") && level flag::get(#"hash_75d94a4065de2749")) {
        } else if (level flag::get(#"hash_75d9474065de2230")) {
            var_888ae42 = struct::get("isle_2_powerup");
        } else if (level flag::get(#"hash_75d94a4065de2749")) {
            var_888ae42 = struct::get("isle_1_powerup");
        } else {
            var_78a8b445 = struct::get("isle_1_powerup");
            var_888ae42 = struct::get("isle_2_powerup");
        }
        break;
    case 1:
        if (level flag::get(#"hash_75d94a4065de2749")) {
            var_888ae42 = struct::get("isle_3_powerup");
        } else {
            var_78a8b445 = struct::get("isle_2_powerup");
            var_888ae42 = struct::get("isle_3_powerup");
        }
        break;
    }
    if (isdefined(var_888ae42)) {
        zm_powerups::specific_powerup_drop("full_ammo", var_888ae42.origin, undefined, undefined, undefined, undefined, 1, undefined, 1);
    }
    if (isdefined(var_78a8b445)) {
        zm_powerups::specific_powerup_drop("carpenter", var_78a8b445.origin, undefined, undefined, undefined, undefined, 1, undefined, 1);
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xea5d9658, Offset: 0x9238
// Size: 0x50
function function_a695c70b(s_loc) {
    if (s_loc.script_int === 1 && level flag::get(#"hash_75d9474065de2230")) {
        return false;
    }
    return true;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x4
// Checksum 0x5ddcd09e, Offset: 0x9290
// Size: 0x1f6
function private function_c7a3202c(str_target_zone) {
    var_d1ac344a = function_3c2238ed(str_target_zone);
    if (!var_d1ac344a) {
        /#
            if (getdvarint(#"zm_debug_ee", 0)) {
                iprintlnbold("<dev string:x6cd>");
            }
        #/
        return false;
    }
    if (var_d1ac344a === self.var_c164e6c7) {
        return true;
    }
    switch (self.var_c164e6c7) {
    case 2:
        if (var_d1ac344a == 3) {
            var_b0e2bf36 = #"aib_vign_cust_zm_red_boss1_stg3_turn_2_to_3_01";
        } else {
            var_b0e2bf36 = #"aib_vign_cust_zm_red_boss1_stg3_turn_2_to_1_01";
        }
        break;
    case 3:
        if (var_d1ac344a == 1) {
            var_b0e2bf36 = #"aib_vign_cust_zm_red_boss1_stg3_turn_3_to_1_01";
        } else {
            var_b0e2bf36 = #"aib_vign_cust_zm_red_boss1_stg3_turn_3_to_2_01";
        }
        break;
    case 1:
        if (var_d1ac344a == 3) {
            var_b0e2bf36 = #"aib_vign_cust_zm_red_boss1_stg3_turn_1_to_3_01";
        } else {
            var_b0e2bf36 = #"aib_vign_cust_zm_red_boss1_stg3_turn_1_to_2_01";
        }
        break;
    }
    s_anchor = struct::get("angles_to_" + self.var_c164e6c7);
    s_anchor scene::play(var_b0e2bf36, level.s_boss_battle.var_d82d0e73);
    self.var_c164e6c7 = var_d1ac344a;
    return true;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x4
// Checksum 0xc2418781, Offset: 0x9490
// Size: 0xbc
function private function_39dc3a09(e_target) {
    v_angles = undefined;
    str_zone = e_target zm_zonemgr::get_player_zone();
    v_angles = 90;
    if (isdefined(str_zone)) {
        switch (str_zone) {
        case #"zone_boss_plateau_1":
            v_angles = 200;
            break;
        case #"zone_boss_plateau_2":
            v_angles = 90;
            break;
        case #"zone_boss_plateau_3":
            v_angles = 309;
            break;
        }
    }
    return (0, v_angles, 0);
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x7ed90142, Offset: 0x9558
// Size: 0x160
function function_766fb0b1(var_fd1c353a) {
    a_enemies = level.ai[#"axis"];
    if (isdefined(a_enemies) && a_enemies.size) {
        a_potential_targets = array::get_all_closest(var_fd1c353a, a_enemies, undefined, undefined, 320);
        if (!isarray(a_potential_targets)) {
            return;
        }
        var_ecfe5e20 = array::filter(a_potential_targets, 0, &function_6c856fde);
        if (var_ecfe5e20.size > 0) {
            foreach (zombie in var_ecfe5e20) {
                if (isdefined(zombie.completed_emerging_into_playable_area) && zombie.completed_emerging_into_playable_area) {
                    zombie zombie_utility::setup_zombie_knockdown(var_fd1c353a);
                }
            }
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xc48a0c58, Offset: 0x96c0
// Size: 0x6
function return_false() {
    return false;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x2fa48d9, Offset: 0x96d0
// Size: 0x88
function function_85593a2(v_point) {
    b_check = 0;
    var_e25fe3db = spawn("script_origin", v_point);
    if (var_e25fe3db istouching(level.s_boss_battle.var_98ea549b)) {
        b_check = 1;
    }
    var_e25fe3db delete();
    return b_check;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xc03d947c, Offset: 0x9760
// Size: 0x224
function perseus_teleport_fx(v_destination) {
    e_sword = level.s_boss_battle.var_5e9e4c15;
    e_perseus = level.s_boss_battle.mdl_perseus;
    v_forward = anglestoforward(e_perseus.angles);
    level waittill(#"play_teleport_tell_fx");
    var_2ff979fa = spawn("script_model", v_destination);
    var_2ff979fa playsound(#"hash_4cc85ba1ffa59d0b");
    playfxontag(level._effect[#"hash_661c427afb24e5f2"], e_perseus, "tag_weapon_right");
    playfx(level._effect[#"hash_4d8d2bc22add9939"], var_2ff979fa.origin, v_forward, (1, 0, 0));
    level waittill(#"play_teleport_fx");
    playsoundatposition(#"hash_5e07cc4ee28c44e7", e_perseus.origin);
    playfx(level._effect[#"hash_65a9f0574c7cd2db"], var_2ff979fa.origin, v_forward, (1, 0, 0));
    playfx(level._effect[#"hash_3d64776928022f66"], e_perseus gettagorigin("j_spine4"), v_forward, (1, 0, 0));
    wait 2;
    var_2ff979fa delete();
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xbeafb348, Offset: 0x9990
// Size: 0x144
function spawn_miniboss() {
    if (math::cointoss(level.s_boss_battle.var_415fc88)) {
        if (math::cointoss(60)) {
            if (zm_ai_blight_father::function_858c7fa5()) {
                zm_transform::function_bdd8aba6(#"blight_father");
                s_waitresult = level waittilltimeout(10, #"transformation_complete");
                if (s_waitresult._notify != "timeout") {
                    function_8b1f9518();
                }
            }
            return;
        }
        if (zombie_gegenees_util::function_48c60fc2()) {
            str_scene = array::random(level.s_boss_battle.var_2624492f);
            level scene::play(str_scene, "targetname");
            function_8b1f9518();
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xc1a83cee, Offset: 0x9ae0
// Size: 0x30
function function_6c856fde(e_zombie) {
    if (e_zombie.zm_ai_category == #"basic") {
        return true;
    }
    return false;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x634f2a46, Offset: 0x9b18
// Size: 0x88
function on_player_connect() {
    foreach (var_de3a312c in level.var_3958c9ff) {
        self thread zm_red_fasttravel::function_28deccf1(var_de3a312c, 1);
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x6c0fab0d, Offset: 0x9ba8
// Size: 0x4fe
function function_6401a80e() {
    self notify("1306ae5632c8627a");
    self endon("1306ae5632c8627a");
    self endon(#"death");
    while (true) {
        s_notify = self waittill(#"hash_1c35eb15aa210d6", #"fasttravel_finished", #"hash_178a3d0115bc972e");
        if (!isdefined(s_notify.var_9fa6220c) || !isdefined(s_notify.var_9fa6220c.script_noteworthy) || s_notify.var_9fa6220c.script_noteworthy != "traverse") {
            continue;
        }
        var_e1284bee = s_notify.var_9fa6220c.s_loc;
        if (!isdefined(var_e1284bee.var_f0bbde5)) {
            foreach (s_loc in level.var_4775015b) {
                if (s_loc.script_string === var_e1284bee.var_7fe26499) {
                    var_e1284bee.var_f0bbde5 = s_loc;
                    break;
                }
            }
        }
        var_f0bbde5 = var_e1284bee.var_f0bbde5;
        var_2d54d86e = s_notify.var_9fa6220c.var_85e825a7;
        switch (s_notify._notify) {
        case #"hash_1c35eb15aa210d6":
            if (isdefined(var_2d54d86e)) {
                level flag::set(var_2d54d86e);
            }
            if (!isdefined(self.var_362f68d6)) {
                self.var_362f68d6 = randomintrange(0, 4);
            }
            if (!self.var_362f68d6) {
                n_char_index = self zm_characters::function_d35e4c92();
                str_vo_alias = "vox_plateau_jump_plr_" + n_char_index;
                a_variants = zm_audio::get_valid_lines(str_vo_alias);
                self.var_2790fd8b thread zm_vo::vo_say(array::random(a_variants), 0, 1, 9999);
                self.var_362f68d6 = randomintrangeinclusive(4, 8);
            } else {
                self.var_362f68d6--;
            }
            if (!(isdefined(var_e1284bee.var_5a099a2d) && var_e1284bee.var_5a099a2d) && !(isdefined(var_e1284bee.var_151f9e4b) && var_e1284bee.var_151f9e4b)) {
                self zm_red_fasttravel::function_28deccf1(var_e1284bee, 2);
            }
            break;
        case #"fasttravel_finished":
            if (isdefined(var_e1284bee.var_151f9e4b) && var_e1284bee.var_151f9e4b || isdefined(var_f0bbde5.var_151f9e4b) && var_f0bbde5.var_151f9e4b) {
                var_e1284bee.unitrigger_stub thread util::delay_notify(0.1, "cancel_fasttravel_cooldown");
                var_f0bbde5.unitrigger_stub thread util::delay_notify(0.1, "cancel_fasttravel_cooldown");
            } else if (!(isdefined(var_f0bbde5.var_5a099a2d) && var_f0bbde5.var_5a099a2d)) {
                self zm_red_fasttravel::function_28deccf1(var_f0bbde5, 2);
            }
            break;
        case #"hash_178a3d0115bc972e":
            if (!(isdefined(var_e1284bee.var_5a099a2d) && var_e1284bee.var_5a099a2d)) {
                self zm_red_fasttravel::function_28deccf1(var_e1284bee, 1);
            }
            if (!(isdefined(var_f0bbde5.var_5a099a2d) && var_f0bbde5.var_5a099a2d)) {
                self zm_red_fasttravel::function_28deccf1(var_f0bbde5, 1);
            }
            break;
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xac4ccece, Offset: 0xa0b0
// Size: 0x134
function function_5fc81f0a(e_target) {
    zm_weap_hand_charon::function_5fc81f0a(e_target);
    zm_weap_hand_gaia::function_5fc81f0a(e_target);
    zm_weap_hand_hemera::function_5fc81f0a(e_target);
    zm_weap_hand_ouranos::function_5fc81f0a(e_target);
    s_result = level waittill(#"hash_4be6553c5ac0ec2b", #"boss_stunned", #"start_thunderstorm", #"hash_78452700119fc913", #"hash_7646638df88a3656");
    zm_weap_hand_charon::function_6d783edd(e_target);
    zm_weap_hand_gaia::function_6d783edd(e_target);
    zm_weap_hand_hemera::function_6d783edd(e_target);
    zm_weap_hand_ouranos::function_6d783edd(e_target);
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x1dc147d9, Offset: 0xa1f0
// Size: 0x168
function function_1722dae1() {
    self notify("4fe6867b112381d6");
    self endon("4fe6867b112381d6");
    level endon(#"hash_71d7e6a55a1ca9e");
    self endon(#"death");
    while (true) {
        s_waitresult = self waittill(#"aoe_damage");
        if (s_waitresult.str_source == "zm_aoe_chaos_bolt" || s_waitresult.str_source == "zm_aoe_chaos_bolt_2") {
            self status_effect::status_effect_apply(level.s_boss_battle.var_b42f3b39, undefined, level.s_boss_battle.mdl_perseus, 0, 3000);
            zm_hero_weapon::function_3fe4a02e(self, 50);
            continue;
        }
        if (s_waitresult.str_source == "zm_aoe_strafe_storm") {
            self status_effect::status_effect_apply(level.s_boss_battle.var_86d9f46c);
            self clientfield::increment_to_player("" + #"hash_3bb8b5cda11eecc6");
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 2, eflags: 0x4
// Checksum 0xcf1a4fe8, Offset: 0xa360
// Size: 0x74
function private function_4c17036d(e_attacker, b_hero_weapon = 0) {
    if (!isdefined(self.var_4bb78ac7) || gettime() > self.var_4bb78ac7) {
        self.var_4bb78ac7 = gettime() + 100;
        e_attacker util::show_hit_marker(b_hero_weapon);
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0xb3975b7e, Offset: 0xa3e0
// Size: 0xd4
function stat_tracker_setup(b_skipped) {
    level endon(#"end_game", #"stat_tracker" + "_ended_early");
    while (!level flag::exists(#"hash_5a7f1f9adac6dc8c") || !level flag::exists(#"boss_battle_complete")) {
        wait 1;
    }
    level flag::wait_till_all(array(#"hash_5a7f1f9adac6dc8c", #"boss_battle_complete"));
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 2, eflags: 0x0
// Checksum 0x3f85189c, Offset: 0xa4c0
// Size: 0x34
function stat_tracker_cleanup(b_skipped, var_19e802fa) {
    level flag::set(#"boss_battle_complete");
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 1, eflags: 0x0
// Checksum 0x437fa88c, Offset: 0xa500
// Size: 0x218
function function_60d4faca(a_s_valid_respawn_points) {
    var_e124a4eb = [];
    foreach (s_respawn_point in a_s_valid_respawn_points) {
        if (s_respawn_point.script_noteworthy == "zone_boss_plateau_2") {
            if (!isdefined(var_e124a4eb)) {
                var_e124a4eb = [];
            } else if (!isarray(var_e124a4eb)) {
                var_e124a4eb = array(var_e124a4eb);
            }
            var_e124a4eb[var_e124a4eb.size] = s_respawn_point;
        }
        if (s_respawn_point.script_noteworthy == "zone_boss_plateau_3" && !level flag::get(#"hash_3e2ec7f6fb6b50c9")) {
            if (!isdefined(var_e124a4eb)) {
                var_e124a4eb = [];
            } else if (!isarray(var_e124a4eb)) {
                var_e124a4eb = array(var_e124a4eb);
            }
            var_e124a4eb[var_e124a4eb.size] = s_respawn_point;
        }
        if (s_respawn_point.script_noteworthy == "zone_boss_plateau_1" && !level flag::get(#"hash_3e2ec4f6fb6b4bb0")) {
            if (!isdefined(var_e124a4eb)) {
                var_e124a4eb = [];
            } else if (!isarray(var_e124a4eb)) {
                var_e124a4eb = array(var_e124a4eb);
            }
            var_e124a4eb[var_e124a4eb.size] = s_respawn_point;
        }
    }
    return var_e124a4eb;
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0xf05a0ac, Offset: 0xa720
// Size: 0x3c
function function_9bc4f8cb() {
    self.spectator_respawn = level.s_boss_battle.registersarah_defeated_gore_[self.playernum];
    self zm_player::spectator_respawn();
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x96f28c7f, Offset: 0xa768
// Size: 0x98
function cleanup_final() {
    wait 1;
    foreach (ai_zombie in getaiteamarray(level.zombie_team)) {
        if (isdefined(ai_zombie)) {
            ai_zombie thread cleanup_zombie();
        }
    }
}

// Namespace red_boss_battle/zm_red_boss_battle
// Params 0, eflags: 0x0
// Checksum 0x7a5f5a69, Offset: 0xa808
// Size: 0x8c
function cleanup_zombie() {
    self endon(#"death");
    self clientfield::increment("" + #"zombie_delete");
    self val::set("cleanup_zombie", "ignoreall", 1);
    wait 0.5;
    self delete();
}

/#

    // Namespace red_boss_battle/zm_red_boss_battle
    // Params 1, eflags: 0x0
    // Checksum 0xdd3c16be, Offset: 0xa8a0
    // Size: 0x15a
    function function_27486895(cmd) {
        switch (cmd) {
        case #"hash_478165f86a3bc512":
            level thread zm_red::function_71a6c3ea();
            level thread function_3a2efd4e(1);
            break;
        case #"hash_a12e7297235e57b":
            level thread function_290d42b8(1);
            break;
        case #"hash_7fe81b8551badbeb":
            level.s_boss_battle.var_5de58d03 = 1;
            break;
        case #"hash_4effcd324e5f7a28":
            setdvar(#"hash_68b9a321eca18c32", 1);
            level thread function_99f0123d();
            break;
        case #"hash_1c090a7b2c262602":
            setdvar(#"hash_68b9a321eca18c32", 0);
            level notify(#"hash_72be9b4e52b943b");
            break;
        }
    }

    // Namespace red_boss_battle/zm_red_boss_battle
    // Params 0, eflags: 0x0
    // Checksum 0x6b819220, Offset: 0xaa08
    // Size: 0xd8
    function function_d5a70078() {
        var_cab6e065 = 0;
        var_9df8166f = 0;
        while (true) {
            if (!var_cab6e065 && getdvarint(#"hash_336a4b6a4bdec400", 0)) {
                var_cab6e065 = 1;
                function_2003ebc9(1);
            }
            if (!var_9df8166f && getdvarint(#"hash_2c5a53140f377a17", 0)) {
                var_9df8166f = 1;
                function_2003ebc9(2);
            }
            wait 0.4;
        }
    }

    // Namespace red_boss_battle/zm_red_boss_battle
    // Params 0, eflags: 0x0
    // Checksum 0x129f9b54, Offset: 0xaae8
    // Size: 0x88
    function function_213d02bd() {
        self notify("<dev string:x6e4>");
        self endon("<dev string:x6e4>");
        self endon(#"death");
        while (true) {
            print3d(self.origin, "<dev string:x6f7>" + self.health, (1, 1, 0), 1, 2, 3);
            wait 0.1;
        }
    }

    // Namespace red_boss_battle/zm_red_boss_battle
    // Params 0, eflags: 0x0
    // Checksum 0x644160b6, Offset: 0xab78
    // Size: 0x28a
    function function_99f0123d() {
        self notify("<dev string:x6fe>");
        self endon("<dev string:x6fe>");
        level endon(#"hash_72be9b4e52b943b");
        while (true) {
            foreach (n_index, e_player in util::get_active_players(#"allies")) {
                n_y_pos = 480 + 18.7 * n_index;
                str_hero_weapon = function_9e72a96(e_player.var_b708af7b);
                if (!isdefined(level.s_boss_battle.var_5015427)) {
                    n_total_damage = 0;
                } else {
                    n_total_damage = level.s_boss_battle.var_5015427[e_player.playernum];
                }
                if (!isdefined(n_total_damage)) {
                    n_total_damage = 0;
                }
                if (!isdefined(str_hero_weapon)) {
                    str_hero_weapon = "<dev string:x48a>";
                }
                debug2dtext((120, n_y_pos, 0), "<dev string:x711>" + n_index + "<dev string:x71a>", (1, 1, 0), 1, (0, 0, 0), 0.4, 1, 2);
                debug2dtext((120 + 100, n_y_pos, 0), str_hero_weapon, (1, 1, 1), 1, (0, 0, 0), 0.4, 1, 2);
                debug2dtext((120 + 240, n_y_pos, 0), n_total_damage, (1, 0, 0), 1, (0, 0, 0), 0.4, 1, 2);
            }
            waitframe(2);
        }
    }

#/
